### ISSUE TITLE
S3 bucket and cdn implementation

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#10]
- [ ] remove 5 image limit on property image listing

- [ ] tweak image fields to save images to s3 bucket

- [ ] load images from cdn

**Comment by mindrootstech** [comment]
Please provide S3 Bucket details with CloudFront setup and AWS login.

**Comment by mnights101** [comment]
Manik, server admin has not responded to my request. Here is the aws login details:here are my aws credentials:
User: info@bnbfusion.com
Pass: mia209gt

**Comment by mindrootstech** [comment]
I logged in but your account setup isnt complete.
Please complete the setup so we can look into setitng up an S3 bucket and its permissions along with cloudfront.

**Comment by mnights101** [comment]
account completed, please proceed

**Comment by mindrootstech** [comment]
The task has been completed. Work done includes:
1. Remove limit of 5 images form create and update listing
2. Change code on create and update to upload images to S3
3. Change code across website to source images form Cloudfront CDN via S3 rather than hard coded server.
4. In search and listing page, change slider images code. Initially, it was coded to only show a max of 5 images but now its dynamic acc to number of images.
5. Upload profile picture to S3 on create/edit user
6. Fetch profile image from CDN across website.

There is screenshot attached showing images being sourced from the CDN now.

Total Effort: $28
![screenshot 2017-02-24 16 08 14](https://cloud.githubusercontent.com/assets/19343942/23300433/87bb7be4-faab-11e6-91f1-86e598ab520b.png)
0

**Comment by mnights101** [comment]
After QA:
Please submit the following corrections:

- [ ] serve images over ssl, currently images are served unsecured, therefore breaking ssl handshake: https://www.bnbfusion.com/resized.php?src=http://d27ykb16d3bcrc.cloudfront.net/1487975554_4_12.jpg&w=230&h=140

- [ ] No profile thumbnail is appearing
![no-profile-thumbnail](https://cloud.githubusercontent.com/assets/10249755/23324645/69ed003c-fac5-11e6-9525-bbef55038302.png)

**Comment by mnights101** [comment]
In addition I just noticed the google map for property  is not showing on desktop or mobile

**Comment by mindrootstech** [comment]
Hi Marco,

The issue of https and profile image not loading is fixed.
For the map, even the default script didnt have map showing on mobile.
On web, the map shows fine.

**Comment by mnights101** [comment]
still getting the same error:
https://www.bnbfusion.com/user/listing/view/NDBfODEwOQ==
![2017-02-28_19-53-40](https://cloud.githubusercontent.com/assets/10249755/23439976/c155347a-fdef-11e6-9649-22b1b6cdf20e.png)
and error also appearing on some listings index:
![2017-02-28_19-34-02](https://cloud.githubusercontent.com/assets/10249755/23440005/e03309f8-fdef-11e6-8b9c-4583401dfe59.png)
